name: Integration

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    name: IntegrationTest
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      pull-requests: write

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: weatherfit_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d weatherfit_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.18.0
        env:
          discovery.type: single-node
          xpack.security.enabled: "false"
          ES_JAVA_OPTS: -Xms512m -Xmx512m
        ports:
          - 9200:9200
        options: >-
          --health-cmd "curl -f http://localhost:9200/_cluster/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    env:
      AWS_S3_ACCESS_KEY: ${{ secrets.AWS_S3_ACCESS_KEY }}
      AWS_S3_SECRET_KEY: ${{ secrets.AWS_S3_SECRET_KEY }}
      AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      WEATHER_ADMINISTRATION_API_KEY: ${{secrets.WEATHER_ADMINISTRATION_API_KEY}}
      KAKAO_API_KEY: ${{secrets.KAKAO_API_KEY}}
      MAIL_HOST: ${{secrets.MAIL_HOST}}
      MAIL_PORT: ${{secrets.MAIL_PORT}}
      MAIL_USERNAME: ${{secrets.MAIL_USERNAME}}
      MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
      MAIL_FROM : ${{secrets.MAIL_FROM}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name : Install JDK 21
        uses : actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Install nori plugin to Elasticsearch
        run: |
          docker exec ${{ job.services.elasticsearch.id }} bin/elasticsearch-plugin install analysis-nori
          docker restart ${{ job.services.elasticsearch.id }}
          sleep 15
          curl -f http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=30s

      - name: Run test
        run: ./gradlew test


